name: GitHub-Profile-Summary-Cards

on:
  schedule: # Roda a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente clicando num botão

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # Escolha o tema que você gosta (dracula, dark, light, etc)
          THEME: dracula